---

- name: create DH parameters
  command: openssl dhparam -out ssl/{{ matrix_synapse_domain }}.dh 2048
  args:
    creates: /opt/synapse/ssl/{{ matrix_synapse_domain }}.dh
    chdir: /opt/synapse
  become_user: synapse
  become: true
