---

hedwig_container_base_volumes:
  - "{{ hedwig_base_path }}:{{ hedwig_base_path }}:ro"

hedwig_container_volumes: "{{ hedwig_container_base_volumes + hedwig_container_extra_volumes }}"

hedwig_container_base_labels:
  version: "{{ hedwig_container_image_tag|default(hedwig_version) }}"
hedwig_container_labels_complete: "{{ hedwig_container_base_labels | combine(hedwig_container_labels) }}"

hedwig_base_config:
  log:
    level: "{{ hedwig_log_level | upper }}"
  server:
    bind_address: "{{ hedwig_server_bind_address }}"
    port: "{{ hedwig_server_port }}"
  hedwig:
    app_id: "{{ hedwig_app_id }}"
    max_jitter_delay: "{{ hedwig_max_jitter_delay }}"
    fcm_push_max_retries: "{{ hedwig_fcm_push_max_retries }}"
    fcm_service_account_token_path: "{{ hedwig_fcm_service_account_file }}"
    fcm_notification_click_action: "{{ hedwig_fcm_notification_click_action }}"
    fcm_notification_title: "{{ hedwig_fcm_notification_title }}"
    fcm_notification_body: "{{ hedwig_fcm_notification_body }}"
    fcm_notification_sound: "{{ hedwig_fcm_notification_body }}"
    fcm_notification_icon: "{{ hedwig_fcm_notification_icon }}"
    fcm_notification_tag: "{{ hedwig_fcm_notification_tag }}"
    fcm_notification_android_channel_id: "{{ hedwig_fcm_notification_android_channel_id }}"
hedwig_config: "{{ hedwig_base_config | combine(hedwig_extra_config) }}"
