---

hedwig_user: hedwig
hedwig_base_path: /opt/hedwig
hedwig_config_file: "{{ hedwig_base_path }}/config.toml"
hedwig_version: "0.1.0"

hedwig_container_name: "hedwig"
hedwig_container_image_name: "registry.gitlab.com/famedly/services/hedwig"
hedwig_container_image: "{{ hedwig_container_image_name }}:{{ hedwig_container_image_tag|default(['v', hedwig_version]|join()) }}"
hedwig_container_env: {}
hedwig_container_ports: []
hedwig_container_labels: {}
hedwig_container_restart_policy: "unless-stopped"
hedwig_container_extra_volumes: []

#hedwig_fcm_admin_key: "my_secret_key_here"
hedwig_listen_port: 7022
hedwig_bind_ip: "::"
#hedwig_app_id: "org.matrix.awesome_client"
hedwig_fcm_collapse_key: "org.matrix.default_notification"
#hedwig_fcm_notification_click_action: "FLUTTER_NOTIFICATION_CLICK"
hedwig_fcm_notification_title: "<count> unread rooms"
hedwig_fcm_notification_body: "Open app to read the messages"
hedwig_fcm_notification_sound: "default"
hedwig_fcm_notification_icon: "notifications_icon"
hedwig_fcm_notification_tag: "org.matrix.default_notification"
hedwig_fcm_notification_android_channel_id: "org.matrix.app.message"
