---
- name: "reload systemd"
  systemd:
    daemon_reload: yes

- name: "restart matrix-synapse"
  service:
    name: "matrix-synapse"
    state: restarted
    enabled: yes

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
