---
- name: Create user
  user:
    name: sygnal
    state: present
  register: sygnal_user

- name: Create base directory
  file:
    path: "{{ sygnal_base_path }}"
    state: directory
    owner: sygnal
    group: sygnal
    mode: "0755"

- name: Deploy sygnal config
  template:
    src: sygnal.yml.j2
    dest: "{{ sygnal_base_path }}/sygnal.yml"
    owner: sygnal
    group: sygnal
    mode: "0600"
  notify: restart-sygnal
