---
livekit_version: "1.8.4"
livekit_jwt_service_version: ""
livekit_jwt_service_container_image_tag: "latest"
livekit_jwt_service_container_enabled: false
livekit_domain: "{{ famedly_instance_domain }}"
livekit_turnserver_domain: ~
livekit_log_level: "info"
livekit_log_sample: true
livekit_metrics_port: 6789
livekit_redis_enabled: false
livekit_ws_port: 7880
livekit_rtc_port: 7881
livekit_rtc_udp_port_start: 50000
livekit_rtc_udp_port_end: 60000
livekit_turns_port: 5349
livekit_turn_port: 3478
livekit_redis_port: 6379
livekit_jwt_service_external_port: 8888
livekit_user: "livekit"
livekit_container_image_reference: >-
  {{
    livekit_container_image_repository
    + ':'
    + livekit_container_image_tag | default('v' + livekit_version)
  }}
livekit_container_image_repository: >-
  {{
    (
      container_registries[livekit_container_image_registry]
      | default(livekit_container_image_registry)
    )
    + '/'
    + livekit_container_image_namespace | default('')
    + livekit_container_image_name
  }}
livekit_container_image_registry: "docker.io"
livekit_container_image_namespace: "livekit/"
livekit_container_image_name: "livekit-server"
livekit_config_path: "/opt/livekit"
livekit_config_file: "livekit.yaml"
livekit_container_config: "/etc/livekit.yaml"
livekit_container_command: "--config {{ livekit_container_config }}"
livekit_config_basic:
  port: "{{ livekit_ws_port }}"
  logging:
    level: "{{ livekit_log_level }}"
    json: true
    sample: "{{ livekit_log_sample }}"
  bind_addresses:
    - "127.0.0.1"
  room:
    enabled_codecs:
      - mime: audio/opus
      - mime: audio/red
      - mime: video/vp8
      - mime: video/h264
      - mime: video/vp9
      - mime: video/av1
  rtc:
    tcp_port: "{{ livekit_rtc_port }}"
    port_range_start: "{{ livekit_rtc_udp_port_start }}"
    port_range_end: "{{ livekit_rtc_udp_port_end }}"
    use_external_ip: true
    congestion_control:
      enabled: true
      allow_pause: true
  turn:
    enabled: true
    domain: "{{ livekit_turnserver_domain }}"
    tls_port: "{{ livekit_turns_port }}"
    udp_port: "{{ livekit_turn_port }}"
    external_tls: true
  keys:
    secret: "{{ livekit_secret_key }}"
  prometheus:
    port: "{{ livekit_metrics_port }}"
livekit_config_redis:
  redis:
    address: "127.0.0.1:{{ livekit_redis_port }}"
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
livekit_config_complete: >-
  {{ livekit_config_basic | combine(livekit_config_redis if (livekit_redis_enabled | bool) else []) }}
livekit_container_name: "livekit"
livekit_container_volumes: []
livekit_container_preset_volumes:
  - "{{ livekit_config_path }}/{{ livekit_config_file }}:{{ livekit_container_config }}:ro"
livekit_container_combined_volumes: >-
  {{ livekit_container_preset_volumes + livekit_container_volumes }}
livekit_container_network_mode: "host"
livekit_jwt_service_container_name: "jwt-service"
livekit_jwt_service_container_image_reference: >-
  {{
    livekit_jwt_service_container_image_repository
    + ':'
    + livekit_jwt_service_container_image_tag | default('v' + livekit_jwt_service_version)
  }}
livekit_jwt_service_container_image_repository: >-
  {{
    (
      container_registries[livekit_jwt_service_container_image_registry]
      | default(livekit_jwt_service_container_image_registry)
    )
    + '/'
    + livekit_jwt_service_container_image_namespace | default('')
    + livekit_jwt_service_container_image_name
  }}
livekit_jwt_service_container_image_registry: "docker-oss.nexus.famedly.de"
livekit_jwt_service_container_image_name: "lk-jwt-service"
livekit_jwt_service_container_env_base:
  LIVEKIT_KEY: "secret"
  LIVEKIT_SECRET: "{{ livekit_secret_key }}"
  LIVEKIT_URL: "wss://{{ livekit_domain }}"
livekit_jwt_service_homeserver_allowlist: []
livekit_jwt_service_container_hs_allowlist:
  HS_ALLOWLIST: "{{ livekit_jwt_service_homeserver_allowlist | join(',') }}"
livekit_jwt_service_container_env: >-
  {{ livekit_jwt_service_container_env_base
    | combine(livekit_jwt_service_container_hs_allowlist
    if (livekit_jwt_service_homeserver_allowlist != []) else {}, recursive=True)
  }}
livekit_jwt_service_container_ports:
  - "127.0.0.1:{{ livekit_jwt_service_external_port }}:8080"
