---
galaxy_info:
  author: Emmanouil Kampitakis (@madonius)
  description: Installs and configures element

  license: AGPL-3.0-or-later

  min_ansible_version: "6"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - matrix
    - element

dependencies: []
