galaxy_info:
  author: Jan Christian Grünhage
  description: Deploys a synapse server

  license: AGPL-3.0-only

  min_ansible_version: "6"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: []

dependencies: []
