---
# tasks file for timetracking-bot
- name: Create timetracking bot user
  user:
    name: matrix-timetracking
    state: present
    system: true
  register: timetracking_bot_user_res

- name: Create application directories
  file:
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ timetracking_bot_user_res.uid }}"
    group: "{{ timetracking_bot_user_res.group }}"
    state: directory
  loop:
    - "{{ timetracking_bot_base_path }}"
    - "{{ timetracking_bot_store_path }}"
    - "{{ timetracking_bot_session_path }}"

- name: Template config
  copy:
    # default required to make linter happy
    content: |
      {{ 'Managed by ansible' | comment('plain', prefix='#####', postfix='#####') }}
      {{ timetracking_bot_config | default({}) | to_nice_yaml }}
    dest: "{{ timetracking_bot_config_path }}"
    mode: "0640"
    owner: "{{ timetracking_bot_user_res.uid }}"
    group: "{{ timetracking_bot_user_res.group }}"
  notify:
    - restart-timetracking-bot

- name: Start container
  community.docker.docker_container:
    name: "timetracking-bot"
    image: "{{ timetracking_bot_container_image_ref }}"
    restart_policy: "unless-stopped"
    user: "{{ timetracking_bot_user_res.uid }}:{{ timetracking_bot_user_res.group }}"
    volumes:
      - "{{ timetracking_bot_config_path }}:{{ timetracking_bot_config_path }}"
      - "{{ timetracking_bot_store_path }}:{{ timetracking_bot_store_path }}"
      - "{{ timetracking_bot_session_path }}:{{ timetracking_bot_session_path }}"
    env: "{{ timetracking_bot_docker_env }}"
    ports: "{{ timetracking_bot_docker_ports }}"
    labels: "{{ timetracking_bot_docker_labels_complete }}"
    command:
      - "/usr/local/bin/timetracker"
      - "-c"
      - "{{ timetracking_bot_config_path }}"
