---
- name: Reload systemd
  systemd:
    daemon_reload: true
  listen: reload-systemd

- name: Restart matrix-synapse using systemd
  service:
    name: matrix-synapse.service
    state: restarted
    enabled: true
  when: matrix_synapse_supervision_method == "systemd"
  listen: restart-matrix-synapse

- name: Restart synapse main container (Docker)
  community.docker.docker_container:
    name: "{{ matrix_synapse_container_name }}"
    state: started
    restart: true
  when: matrix_synapse_supervision_method == "docker"
  listen: restart-matrix-synapse

- name: Wait for synapse main to become healthy (Docker)
  ansible.builtin.uri:
    url: "{{ matrix_synapse_healthcheck_url }}"
    status_code: 200
  register: matrix_synapse_healthcheck
  until: matrix_synapse_healthcheck is successful
  retries: "{{ matrix_synapse_healthcheck_retries }}"
  delay: "{{ matrix_synapse_healthcheck_delay }}"
  when:
    - matrix_synapse_supervision_method == "docker"
    - matrix_synapse_workers | default([]) | length > 0
  listen: restart-matrix-synapse

- name: Restart synapse worker containers (docker)
  community.docker.docker_container:
    name: "{{ item }}"
    state: started
    restart: true
  loop: "{{ matrix_synapse_workers | default([]) | map(attribute='container_name') | list }}"
  when:
    - matrix_synapse_supervision_method == "docker"
    - matrix_synapse_workers | default([]) | length > 0
  listen: restart-matrix-synapse

- name: Restart rsyslog
  become: true
  service:
    name: rsyslog
    state: restarted
  when: matrix_synapse_supervision_method == "systemd"
  listen: restart-rsyslog
