---
- name: Reload systemd
  systemd:
    daemon_reload: true
  listen: reload-systemd

- name: Restart matrix-synapse using systemd
  service:
    name: matrix-synapse.service
    state: restarted
    enabled: true
  when: matrix_synapse_supervision_method == "systemd"
  listen: restart-matrix-synapse

- name: Restart synapse using docker
  community.docker.docker_container:
    name: "{{ matrix_synapse_container_name }}"
    state: started
    restart: true
  when: matrix_synapse_supervision_method == "docker"
  listen: restart-matrix-synapse
  loop: >-2
    {{ [matrix_synapse_container_name]
    + matrix_synapse_workers | default([]) | map(attribute='container_name') }}

- name: Restart rsyslog
  become: true
  service:
    name: rsyslog
    state: restarted
  when: matrix_synapse_supervision_method == "systemd"
  listen: restart-rsyslog
