---

- name: Create howler system user
  user:
    name: "{{ howler_user }}"
    state: present
    system: yes
  register: howler_user_res

- name: Ensure host directories are present
  file:
    path: "{{ howler_base_path }}"
    state: directory
    owner: "{{ howler_user_res.uid }}"
    group: "{{ howler_user_res.group }}"

- name: Template configuration file for howler
  template:
    src: config.toml.j2
    dest: "{{ howler_config_file }}"
    owner: "{{ howler_user_res.uid }}"
    group: "{{ howler_user_res.group }}"
    mode: 0770

- name: Start howler container
  docker_container:
    name: "{{ howler_container_name }}"
    image: "{{ howler_container_image }}"
    env: "{{ howler_container_env }}"
    user: "{{ howler_user_res.uid }}:{{ howler_user_res.group }}"
    ports: "{{ howler_container_ports }}"
    labels: "{{ howler_container_labels }}"
    volumes: "{{ howler_container_volumes }}"
    restart_policy: "{{ howler_container_restart_policy }}"
    pull: true
