---
galaxy_info:
  author: Jan Christian Grünhage <jan.christian@gruenhage.xyz>
  description: Install Sygnal (Matrix push gateway sever)

  license: AGPLv3

  min_ansible_version: "6"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: []

dependencies: []
