---

- name: Create hedwig system user
  user:
    name: "{{ hedwig_user }}"
    state: present
    system: yes
  register: hedwig_user_res
  tasks: ['prepare', 'prepare-hedwig']

- name: Ensure host directories are present
  file:
    path: "{{ hedwig_base_path }}"
    state: directory
    owner: "{{ hedwig_user_res.uid }}"
    group: "{{ hedwig_user_res.group }}"
  tasks: ['prepare', 'prepare-hedwig']

- name: Template configuration file for hedwig
  copy:
    content: "{{ hedwig_config | to_nice_yaml(indent=2, width=1000) }}"
    dest: "{{ hedwig_config_file }}"
    owner: "{{ hedwig_user_res.uid }}"
    group: "{{ hedwig_user_res.group }}"
    mode: 0770
  notify: restart-hedwig
  tasks: ['configure', 'configure-hedwig']

- name: Ensure hedwig container image is present
  docker_image:
    name: "{{ hedwig_container_image }}"
    force_source: "{{ hedwig_container_image_force_pull | default(True) }}"
    source: pull
    state: present
  tasks: ['prepare', 'prepare-hedwig']

- name: Ensure hedwig container is started
  docker_container:
    name: "{{ hedwig_container_name }}"
    image: "{{ hedwig_container_image }}"
    env: "{{ hedwig_container_env }}"
    user: "{{ hedwig_user_res.uid }}:{{ hedwig_user_res.group }}"
    ports: "{{ hedwig_container_ports }}"
    labels: "{{ hedwig_container_labels_complete }}"
    volumes: "{{ hedwig_container_volumes }}"
    restart_policy: "{{ hedwig_container_restart_policy }}"
    healthcheck:
      test: "curl http://127.0.0.1:{{ hedwig_server_port }}/health || exit 1"
    state: started
  tasks: ['deploy', 'deploy-hedwig']
