---
- name: Reload systemd
  systemd:
    daemon_reload: true
  listen: reload-systemd

- name: Restart sygnal using systemd
  service:
    name: "sygnal"
    state: restarted
    enabled: true
  when: sygnal_supervision_method == "systemd"
  listen: "restart-sygnal"

- name: Restart sygnal using docker
  community.docker.docker_container:
    name: sygnal
    state: started
    restart: true
  when: sygnal_supervision_method == "docker"
  listen: "restart-sygnal"
