---

- name: Build homeserver media worker override
  set_fact:
    matrix_synapse_media_worker_override:
      enable_media_repo: False
      media_instance_running_background_jobs: "worker_media_1"
  when: matrix_synapse_workers_media|int > 0

- name: Register all federation senders to synapse
  set_fact:
    matrix_synapse_worker_fed_senders: >-2
      {{ matrix_synapse_worker_fed_senders | default([])
      +
      [ ('worker_fed_out_' + item | string) ] }}
  loop: "{{ range(1, matrix_synapse_workers_federation_out + 1) | list }}"
  loop_control:
    label: "worker_fed_out_{{ item | string }}"

- name: Build homeserver federation override
  set_fact:
    matrix_synapse_fed_sender_override:
      send_federation: False
      federation_sender_instances: "{{ matrix_synapse_worker_fed_senders }}"
  when: matrix_synapse_workers_federation_out|int > 0

- name: Build homeserver pusher override
  set_fact:
    matrix_synapse_pusher_override:
      pusher_instances: "worker_pusher"
  when: matrix_synapse_worker_push

- name: Merge worker config into homeserver config
  set_fact:
    matrix_synapse_worker_config: >-2
      {{
        [ matrix_synapse_worker_config,
          matrix_synapse_media_worker_override,
          matrix_synapse_fed_sender_override,
          matrix_synapse_pusher_override
        ] | combine(recursive=True)
      }}
