---
- name: Install signedjson
  ansible.builtin.apt:
    name: python3-signedjson
  tags: ['prepare', 'prepare-synapse']
  when: ansible_distribution == "Debian"

- name: Create signing key
  matrix_signing_key:
    path: "{{ matrix_synapse_config.signing_key_path }}"
  notify: "restart-matrix-synapse"
  tags: ['deploy', 'deploy-synapse']

- name: Write server's certificate and private key
  when: not matrix_synapse_config.no_tls
  tags: ['deploy', 'deploy-synapse']
  block:
    - name: Create DH parameters
      community.crypto.openssl_dhparam:
        path: "{{ matrix_synapse_dh_path }}"
        owner: synapse
    - name: Write certificate
      copy:
        content: "{{ matrix_synapse_tls_cert }}"
        dest: "{{ matrix_synapse_config.tls_certificate_path }}"
        owner: synapse
        group: synapse
        mode: "0644"
    - name: Write keyfile
      copy:
        content: "{{ matrix_synapse_tls_key }}"
        dest: "{{ matrix_synapse_config.tls_private_key_path }}"
        owner: synapse
        group: synapse
        mode: "0600"
