---
- name: Create appservice group
  group:
    name: "matrix-appservices"
    state: present
    system: true
  register: appservice_group

- name: Create user
  user:
    name: synapse
    state: present
    groups: [matrix-appservices]
    append: true
  register: synapse_user

- name: Create directory
  file:
    path: "{{ matrix_synapse_base_path }}"
    state: directory
    owner: synapse
    group: synapse
    mode: "0750"
