---
- name: Create appservice group
  group:
    name: "{{ item }}"
    state: present
    system: true
  register: appservice_group
  loop: "{{ matrix_synapse_appservice_groups }}"

- name: Create user
  user:
    name: synapse
    state: present
    groups: "{{ matrix_synapse_appservice_groups }}"
    append: true
  register: synapse_user

- name: Create directory
  file:
    path: "{{ matrix_synapse_base_path }}"
    state: directory
    owner: synapse
    group: synapse
    mode: "0750"
