---
- name: Deploy service file
  template:
    src: "matrix-synapse.service.j2"
    dest: "/etc/systemd/system/matrix-synapse.service"
    mode: "0644"
  notify: ["reload-systemd", "restart-matrix-synapse"]
